# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Sam Yonski"
description: > # this means to ignore newlines until "email:"
   Reading and writing...

email: sam.yonski@gmail.com
#blog logo
logo: "/assets/images/sam_yonski_logo.png"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Sam Yonski'
author: 'Sam Yonski'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://ofcan.github.io" # the base hostname & protocol for your site
baseurl: /sam_yonski

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/samyonski
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/samyonski
#    desc: Connect with me on facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
